### ISSUE TITLE
Create a sharer page which is generating the "I'm going to the open source day conference" image

### ISSUE THREAD

**Issue by TheJoin95** [Schrodinger-Hat/osday#112]
As it is for other conferences, such as nextjs, wearedevs, and big conf, it will be good if we can make a button or a page where the user can get its ticket with its name to share it then on the social media.

e.g.
![image](https://user-images.githubusercontent.com/6616203/206327707-d7f5dcd9-1d90-425f-ac99-b9f1b2297a29.png)

**Comment by Wabri** [comment]
Since tickets are generated by eventbrite, how do you create this other of ticket? Do you want use eventbrite api? Or simply let the user create the ticket without worrying that it has a real ticket on eventbrite?

**Comment by TheJoin95** [comment]
We have options:
- check if on eventbrite we can customize the UX to redirect to our webpage
- make a form where the user is giving us the email and we check evenbrite to gave back the fake UI ticket
- make a form where the user is giving us the email, without checking it, and gave back the fake UI ticket with a message to buy the ticket on evenbrite
