### ISSUE TITLE
Create OSDay 2024 website, move OSDay 2023 as previous edition

### ISSUE THREAD

**Issue by nicpuppa** [Schrodinger-Hat/osday#252]

**Comment by Wabri** [comment]
We can make a version with tag name osday23 and use that to deploy in 2023.osday.dev and the master branch for osday.dev

**Comment by TheJoin95** [comment]
We need to check this, but I do remember the possibility of deploying a tag.

My concerns is to move the osday website from my personal account to
Schrodinger account

**Comment by Wabri** [comment]
We think that is necessary for this year to keep the same theme by completing the features that remained from last year

**Comment by nicpuppa** [comment]
@TheJoin95 this is done right ?
