### ISSUE TITLE
Add easter egg on profile image

### ISSUE THREAD

**Issue by TheJoin95** [Schrodinger-Hat/osday#35]

**Comment by nicpuppa** [comment]
@TheJoin95 can you please give more information ?

**Comment by TheJoin95** [comment]
We can add a tooltip saying: "Would you like to discover more on quantum theory? Click me" then if the user will click on the profile image will be redirect to our spreadshirt store, that needs to be created. So for now, just add the tooltip and a link to "shop.osday.dev" in a target _blank
